<a href="https://colab.research.google.com/github/jathusiya/MachineLearningToturial/blob/master/Fake_News.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn .linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [34]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [35]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [37]:
#data pre-processing
news_dataset =pd.read_csv('/content/fake_news.csv', nrows=4100)

/tmp/ipykernel_140/1604558924.py:2: DtypeWarning: Columns (1,10,12,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,115,117,123) have mixed types. Specify dtype option on import or set low_memory=False.
  news_dataset =pd.read_csv('/content/fake_news.csv', nrows=4100)

In [38]:
news_dataset.shape

(4100, 699)

In [39]:
news_dataset.head()

                                       uuid  ... Unnamed: 698
0  6a175f46bcd24d39b3e962ad0f29936721db70db  ...          NaN
1  2bdc29d12605ef9cf3f09f9875040a7113be5d5b  ...          NaN
2  c70e149fdd53de5e61c29281100b9de0ed268bc3  ...          NaN
3  7cf7c15731ac2a116dd7f629bd57ea468ed70284  ...          NaN
4  0206b54719c7e241ffe0ad4315b808290dbe6c0f  ...          NaN

[5 rows x 699 columns]

In [40]:
news_dataset.isnull().sum()

uuid                0
ord_in_thread     117
author            861
published         245
title             638
                 ...
Unnamed: 694     4100
Unnamed: 695     4100
Unnamed: 696     4100
Unnamed: 697     4100
Unnamed: 698     4100
Length: 699, dtype: int64

In [41]:
#replacing null value with empty strings
news_dataset=news_dataset.fillna('')

In [42]:
from types import new_class
#merging author name and news title
news_dataset['content'] = news_dataset['author']+' '+news_dataset['title']

/tmp/ipykernel_140/2488965215.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  news_dataset['content'] = news_dataset['author']+' '+news_dataset['title']

In [43]:
print(news_dataset[('content')])

0       Barracuda Brigade Muslims BUSTED: They Stole M...
1       reasoning with facts Re: Why Did Attorney Gene...
2       Barracuda Brigade BREAKING: Weiner Cooperating...
3       Fed Up PIN DROP SPEECH BY FATHER OF DAUGHTER K...
4       Fed Up FANTASTIC! TRUMP'S 7 POINT PLAN To Refo...
                              ...
4095    Hal Apeeno 6 MILLION John Niems Authorised Ver...
4096    JENO Jury acquits leaders of Oregon standoff o...
4097    Joe from MassPrivateI PATRIOT Act At 15: Do Yo...
4098    Joe from MassPrivateI News Shot: Detroit Airpo...
4099    Angel - NYC Shots reportedly fired, 141 arrest...
Name: content, Length: 4100, dtype: object

In [44]:
#seperating the data& label
x= news_dataset.drop(columns='spam_score', axis=1)
y= news_dataset['spam_score']

In [45]:
print(x)
print(y)

                                          uuid  ...                                            content
0     6a175f46bcd24d39b3e962ad0f29936721db70db  ...  Barracuda Brigade Muslims BUSTED: They Stole M...
1     2bdc29d12605ef9cf3f09f9875040a7113be5d5b  ...  reasoning with facts Re: Why Did Attorney Gene...
2     c70e149fdd53de5e61c29281100b9de0ed268bc3  ...  Barracuda Brigade BREAKING: Weiner Cooperating...
3     7cf7c15731ac2a116dd7f629bd57ea468ed70284  ...  Fed Up PIN DROP SPEECH BY FATHER OF DAUGHTER K...
4     0206b54719c7e241ffe0ad4315b808290dbe6c0f  ...  Fed Up FANTASTIC! TRUMP'S 7 POINT PLAN To Refo...
...                                        ...  ...                                                ...
4095  a2f0db0a8b85901369a654416fb2ed2d49b169b9  ...  Hal Apeeno 6 MILLION John Niems Authorised Ver...
4096  5d24f1d02ab5c2e8f42961527b27300f485da92d  ...  JENO Jury acquits leaders of Oregon standoff o...
4097  640b2d6a9a8238ba6919f3192c33240ce8511a58  ...  Joe from MassPrivateI PATRIOT Act At 15: Do Yo...
4098  e57c05f91bae12a39426e2d7d76ccb3ac36173eb  ...  Joe from MassPrivateI News Shot: Detroit Airpo...
4099  41b95fcab1166aa6d5c51642bd31ad92dada5ad4  ...  Angel - NYC Shots reportedly fired, 141 arrest...

[4100 rows x 699 columns]
0           0
1           0
2           0
3       0.068
4       0.865
        ...
4095        0
4096        0
4097        0
4098        0
4099        0
Name: spam_score, Length: 4100, dtype: object

In [46]:
#stemming
port_stem = PorterStemmer()

In [ ]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]', ' ' ,content)
  stemmed_content=stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content =' '.join(stemmed_content)
  return stemmed_content